# Generated by Django 5.1.4 on 2024-12-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uibill', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': '交易记录', 'verbose_name_plural': '交易记录'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category_code',
            field=models.CharField(choices=[('A', '生活'), ('B', '聚餐'), ('C', '烟酒'), ('D', '用品'), ('E', '穿搭'), ('F', '房租'), ('G', '水费'), ('H', '电费'), ('I', '网费'), ('J', '出行'), ('K', '投资'), ('L', '收入')], max_length=1, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=200, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('1', '微信'), ('2', '支付宝'), ('3', '现金'), ('4', '京东白条'), ('5', '交通银行信用卡'), ('6', '农商行信用卡'), ('7', '其他银行卡')], max_length=1, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(verbose_name='交易日期'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
